/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kkpridwan;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lullaby
 */
public class logenkrip extends javax.swing.JInternalFrame {
    /**
     * Creates new form logenkrip
     */
    public logenkrip() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblenkrip = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(801, 600));

        tblenkrip.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jam", "Tanggal", "Nama File", "Size File (kb)", "Sumber", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblenkrip);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void getisiTable(String user){
Object header[]={"Jam","Tanggal","Nama File","Size File","Sumber","password"};
DefaultTableModel data = new DefaultTableModel(null, header);
tblenkrip.setModel(data);
   try {
       
       Koneksi objKoneksi = new Koneksi();		
			Connection con = objKoneksi.bukaKoneksi();
			Statement st = con.createStatement();
			String sql = "select * from log where username='"+user+"' and jns_aksi='Enkrip'";
			ResultSet rs = st.executeQuery(sql);
	while(rs.next()){
	String kolom1 = rs.getString("jam");
           String kolom2 = rs.getString("tgl");
           String kolom3 = rs.getString("nm_file");
           String kolom4 = rs.getString("size_file");
           String kolom5 = rs.getString("sumber");
           String kolom6 = rs.getString("cipherkey");    
           String kolom[] = {kolom1, kolom2, kolom3, kolom4, kolom5, kolom6};
           data.addRow(kolom);
			}
   }catch (Exception e){
        JOptionPane.showMessageDialog(null,"error :"+e.getMessage());
        } 
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblenkrip;
    // End of variables declaration//GEN-END:variables
}
